apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
spec:
  serviceName: {{ template "fullname" . }}
  replicas: {{default 5 .Values.Replicas }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-{{.Values.Component}}"
      {{if .Values.AWS.Kube2IAMAccountName }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.AWS.Kube2IAMAccountName | quote }}
      {{end}}
    spec:
      {{if .Values.ServiceAccountName }}
      serviceAccountName: {{ .Values.ServiceAccountName | quote }}
      {{end}}
      containers:
      - name: spilo
        image: "{{ .Values.Spilo.Image }}:{{ .Values.Spilo.Version }}"
        env:
        - name: PGPASSWORD_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: password-superuser
        - name: PGPASSWORD_ADMIN
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: password-admin
        - name: PGPASSWORD_STANDBY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: password-standby
        {{if .Values.Etcd.Host }}
        - name: ETCD_HOST
          value: {{ .Values.Etcd.Host | quote }}
        {{else}}
        - name: ETCD_DISCOVERY_DOMAIN
          value: {{default (printf "%s-etcd" .Release.Name | trunc 63) .Values.Etcd.Discovery }}
        {{end}}
        - name: SCOPE
          value: {{ template "fullname" . }}
        {{if .Values.AWS.S3BucketName }}
        - name: WAL_S3_BUCKET
          value: {{ .Values.AWS.S3BucketName | quote }}
        {{end}}
        - name: PGROOT
          value: /home/postgres/pgdata/pgroot
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8008
        - containerPort: 5432
        resources:
          requests:
            cpu: "{{.Values.Resources.Cpu}}"
            memory: "{{.Values.Resources.Memory}}"
        volumeMounts:
        - name: pgdata
          mountPath: /home/postgres/pgdata
        - mountPath: /etc/patroni
          name: patroni-config
          readOnly: true
      volumes:
      - name: patroni-config
        secret:
          secretName: {{ template "fullname" . }}
  volumeClaimTemplates:
  - metadata:
      name: pgdata
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "{{.Values.Resources.Storage}}"
